services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maieutix_prod
      POSTGRES_USER: maieutix_user
      POSTGRES_PASSWORD: maieutix_password
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maieutix_user -d maieutix_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=maieutix.settings
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=False
      - POSTGRES_DB=maieutix_prod
      - POSTGRES_USER=maieutix_user
      - POSTGRES_PASSWORD=maieutix_password
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: