# Generated by Django 5.2.5 on 2025-08-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('rue', models.CharField(max_length=255, verbose_name='Rue')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1. Cabinet',
                'verbose_name_plural': '1. Cabinet',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='SageFemme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('rue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rue')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('numero_cafat', models.CharField(max_length=50, verbose_name='Numéro CAFAT')),
                ('ridet', models.CharField(max_length=50, verbose_name='RIDET')),
                ('rib', models.CharField(max_length=100, verbose_name='RIB')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('situation', models.CharField(choices=[('gerant', 'Gérant'), ('collaborateur', 'Collaborateur'), ('remplacant', 'Remplaçant')], max_length=20, verbose_name='Situation')),
                ('etat_recapitulatif_commun', models.BooleanField(default=False, help_text="Cocher si l'état récapitulatif est commun avec le titulaire", verbose_name='État récapitulatif commun avec le titulaire')),
                ('bons_depot_communs', models.BooleanField(default=False, help_text='Cocher si les bons de dépôt sont communs avec le titulaire', verbose_name='Bons de dépôt communs avec le titulaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('remplacement_de', models.ForeignKey(blank=True, help_text='Sage-femme remplacée (seulement pour les remplaçants)', limit_choices_to={'situation__in': ['gerant', 'collaborateur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sagefemme', verbose_name='Remplacement de')),
            ],
            options={
                'verbose_name': 'Sage-femme',
                'verbose_name_plural': 'Sages-femmes',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
