# Generated by Django 5.2.5 on 2025-08-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sagefemme',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': '2. Sage-femme', 'verbose_name_plural': '2. Sages-femmes'},
        ),
        migrations.CreateModel(
            name='PeriodeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date de début de la période d'activité (obligatoire)", verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de la période d'activité (facultative). Si vide, la période est considérée comme en cours.", null=True, verbose_name='Date de fin')),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire sur cette période d'activité", verbose_name='Commentaire')),
                ('sage_femme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_activite', to='core.sagefemme', verbose_name='Sage-femme')),
            ],
            options={
                'verbose_name': "Période d'activité",
                'verbose_name_plural': "Périodes d'activité",
                'ordering': ['-date_debut'],
            },
        ),
    ]
