# Generated by Django 5.2.5 on 2025-08-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sagefemme_options_periodeactivite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodeactivite',
            options={'ordering': ['-date_debut'], 'verbose_name': "2.1 Période d'activité", 'verbose_name_plural': "2.1 Périodes d'activité"},
        ),
    ]
