# Generated by Django 5.2.5 on 2025-08-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_periode_activite_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sagefemme',
            name='remplacement_de',
            field=models.ForeignKey(blank=True, help_text='Sage-femme remplacée (seulement pour les remplaçants)', limit_choices_to={'situation__in': ['titulaire', 'collaborateur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sagefemme', verbose_name='Remplacement de'),
        ),
        migrations.AlterField(
            model_name='sagefemme',
            name='situation',
            field=models.CharField(choices=[('titulaire', 'Titulaire'), ('collaborateur', 'Collaborateur'), ('remplacant', 'Remplaçant')], max_length=20, verbose_name='Situation'),
        ),
    ]
