# Generated by Django 5.2.5 on 2025-08-17 21:22

from django.db import migrations


def migrate_gerant_to_titulaire(apps, schema_editor):
    """
    Migre les données existantes de 'gerant' vers 'titulaire'
    """
    SageFemme = apps.get_model('core', 'SageFemme')
    
    # Mettre à jour toutes les sages-femmes avec situation='gerant' vers 'titulaire'
    SageFemme.objects.filter(situation='gerant').update(situation='titulaire')


def reverse_migrate_titulaire_to_gerant(apps, schema_editor):
    """
    Migration inverse : retourne 'titulaire' vers 'gerant'
    """
    SageFemme = apps.get_model('core', 'SageFemme')
    
    # Retourner toutes les sages-femmes avec situation='titulaire' vers 'gerant'
    SageFemme.objects.filter(situation='titulaire').update(situation='gerant')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_change_gerant_to_titulaire'),
    ]

    operations = [
        migrations.RunPython(
            migrate_gerant_to_titulaire,
            reverse_migrate_titulaire_to_gerant
        ),
    ]
