# Generated by Django 5.2.5 on 2025-08-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrate_gerant_data_to_titulaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagefemme',
            name='is_active',
        ),
    ]
