# Generated by Django 5.2.5 on 2025-08-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagefemme',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si la sage-femme est active', verbose_name='Actif'),
        ),
    ]
