# Generated by Django 5.2.5 on 2025-08-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sagefemme_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodeactivite',
            options={'ordering': ['-date_debut'], 'verbose_name': "Période d'activité", 'verbose_name_plural': "Périodes d'activité"},
        ),
        migrations.AddField(
            model_name='sagefemme',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur pour la connexion', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
