# Generated by Django 5.2.5 on 2025-08-28 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_periodeactivite_options_sagefemme_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code court identifiant l'acte (ex: CSF, VGC, etc.)", max_length=20, unique=True, verbose_name='Code acte')),
                ('libelle', models.TextField(help_text="Description complète de l'acte", verbose_name='Libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': '4. Acte',
                'verbose_name_plural': '4. Actes',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='periodeactivite',
            options={'ordering': ['-date_debut'], 'verbose_name': "2.1 Période d'activité", 'verbose_name_plural': "2.1 Périodes d'activité"},
        ),
        migrations.CreateModel(
            name='TarifPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_xpf', models.DecimalField(decimal_places=0, help_text='Montant en francs CFP', max_digits=10, verbose_name='Coût conventionnel (XPF)')),
                ('date_debut', models.DateField(help_text='Date de début de validité du tarif', verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de validité (laisser vide pour un tarif permanent)', null=True, verbose_name='Date de fin')),
                ('commentaire', models.TextField(blank=True, help_text='Notes sur cette période tarifaire', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_periodes', to='core.acte', verbose_name='Acte')),
            ],
            options={
                'verbose_name': '5. Tarif période',
                'verbose_name_plural': '5. Tarifs périodes',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='date_fin_apres_date_debut')],
            },
        ),
    ]
