# Generated by Django 5.2.5 on 2025-08-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acte_alter_periodeactivite_options_tarifperiode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acte',
            options={'ordering': ['code'], 'verbose_name': '3. Acte', 'verbose_name_plural': '3. Actes'},
        ),
        migrations.AlterModelOptions(
            name='tarifperiode',
            options={'ordering': ['-date_debut'], 'verbose_name': '3.1 Tarif Acte', 'verbose_name_plural': '3.1 Tarifs Actes'},
        ),
    ]
