# Generated by Django 5.2.5 on 2025-08-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_acte_options_alter_tarifperiode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifperiode',
            name='commentaire',
        ),
    ]
