# Generated by Django 5.2.5 on 2025-08-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_commentaire_from_tarifperiode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadreExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Nom du cadre d'exercice", max_length=200, verbose_name='Label')),
                ('description', models.TextField(help_text="Description détaillée du cadre d'exercice", verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "4. Cadre d'exercice",
                'verbose_name_plural': "4. Cadres d'exercice",
                'ordering': ['label'],
            },
        ),
    ]
