# Generated by Django 5.2.5 on 2025-08-30 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cadreexercice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadreexercice',
            options={'ordering': ['label'], 'verbose_name': "4.1 Cadre d'exercice", 'verbose_name_plural': "4.1 Cadres d'exercice"},
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(help_text='Description de la prestation', verbose_name='Désignation')),
                ('limite', models.TextField(blank=True, help_text='Limites ou contraintes de la prestation', null=True, verbose_name='Limite')),
                ('cotation', models.DecimalField(decimal_places=2, help_text='Valeur de cotation de la prestation', max_digits=10, verbose_name='Cotation')),
                ('entente_prealable', models.TextField(help_text="Conditions d'entente préalable", verbose_name='Entente préalable')),
                ('assurance_maladie', models.TextField(blank=True, help_text='Informations sur la prise en charge assurance maladie', null=True, verbose_name='Assurance maladie')),
                ('assurance_maternite_normale', models.TextField(blank=True, help_text='Informations sur la prise en charge maternité normale', null=True, verbose_name='Assurance maternité normale')),
                ('assurance_maternite_pathologie', models.TextField(blank=True, help_text='Informations sur la prise en charge maternité pathologique', null=True, verbose_name='Assurance maternité pathologie')),
                ('observation', models.TextField(blank=True, help_text='Observations particulières', null=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('actes', models.ManyToManyField(blank=True, help_text='Actes associés à cette prestation', to='core.acte', verbose_name='Actes')),
                ('cadre_exercice', models.ForeignKey(help_text="Cadre d'exercice associé à cette prestation", on_delete=django.db.models.deletion.CASCADE, to='core.cadreexercice', verbose_name="Cadre d'exercice")),
            ],
            options={
                'verbose_name': '4. Prestation',
                'verbose_name_plural': '4. Prestations',
                'ordering': ['cadre_exercice__label', 'designation'],
            },
        ),
    ]
