# Generated by Django 5.2.5 on 2025-08-30 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cadreexercice_options_prestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestation',
            name='actes',
        ),
        migrations.AddField(
            model_name='prestation',
            name='acte',
            field=models.ForeignKey(default=1, help_text='Acte associé à cette prestation', on_delete=django.db.models.deletion.CASCADE, to='core.acte', verbose_name='Acte'),
        ),
    ]
