# Generated by Django 5.2.5 on 2025-08-31 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_change_actes_to_acte'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si la prestation est active', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='origine',
            field=models.CharField(blank=True, choices=[('', 'Vide'), ('LM', 'LM'), ('AT', 'AT'), ('MT', 'MT'), ('GP', 'GP')], default='', help_text='Origine de la prestation', max_length=2, verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='prescription',
            field=models.BooleanField(default=False, help_text='Indique si une prescription est nécessaire', verbose_name='Prescription'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='suffixe',
            field=models.CharField(blank=True, help_text='Suffixe facultatif pour la prestation', max_length=50, null=True, verbose_name='Suffixe'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='acte',
            field=models.ForeignKey(help_text='Acte associé à cette prestation', on_delete=django.db.models.deletion.CASCADE, to='core.acte', verbose_name='Acte'),
        ),
    ]
