# Generated by Django 5.2.5 on 2025-09-01 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_prestation_actif_prestation_origine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage à payer (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_paiement', to='core.sagefemme', verbose_name='Titulaire')),
            ],
            options={
                'verbose_name': 'Condition de paiement',
                'verbose_name_plural': 'Conditions de paiement',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la caisse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='core.sagefemme', verbose_name='Titulaire')),
                ('conditions_paiement_eligibles', models.ManyToManyField(blank=True, related_name='caisses_eligibles', to='core.conditionpaiement', verbose_name='Conditions de paiement éligibles')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['nom'],
            },
        ),
    ]
