# Generated by Django 5.2.5 on 2025-09-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_conditionpaiement_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionpaiement',
            name='titulaire',
        ),
    ]
