# Generated by Django 5.2.5 on 2025-09-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_conditionpaiement_titulaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='titulaire',
        ),
    ]
