# Generated by Django 5.2.5 on 2025-09-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_caisse_description_remove_caisse_titulaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['nom'], 'verbose_name': '5. Caisse', 'verbose_name_plural': '5. Caisses'},
        ),
        migrations.AlterModelOptions(
            name='conditionpaiement',
            options={'ordering': ['designation'], 'verbose_name': '5.1 Condition de paiement', 'verbose_name_plural': '5.1 Conditions de paiement'},
        ),
    ]
