# Generated by Django 5.2.5 on 2025-09-03 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_caisse_options_alter_conditionpaiement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_patient', models.CharField(choices=[('femme', 'Femme'), ('bebe', 'Bébé')], max_length=10, verbose_name='Type de patient')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('nom_jf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de jeune fille')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Format: 0123456789 ou +33123456789', regex='^(\\+33|0)[1-9](\\d{8})$')], verbose_name='Téléphone')),
                ('numero_ep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro EP')),
                ('date_debut_grossesse', models.DateField(blank=True, help_text='Uniquement pour les femmes', null=True, verbose_name='Date de début de grossesse')),
                ('est_assure_titulaire', models.BooleanField(default=True, verbose_name='Assuré titulaire')),
                ('nom_assure', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'assuré")),
                ('prenom_assure', models.CharField(blank=True, max_length=100, null=True, verbose_name="Prénom de l'assuré")),
                ('date_naissance_assure', models.DateField(blank=True, null=True, verbose_name="Date de naissance de l'assuré")),
                ('rue_assure', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue (assuré)')),
                ('code_postal_assure', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Le code postal doit contenir 5 chiffres', regex='^\\d{5}$')], verbose_name='Code postal (assuré)')),
                ('commune_assure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune (assuré)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caisse', verbose_name="Caisse d'assurance")),
                ('mere', models.ForeignKey(blank=True, help_text='Uniquement pour les bébés', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bebes', to='core.patient', verbose_name='Mère')),
            ],
            options={
                'verbose_name': '6. Patient',
                'verbose_name_plural': '6. Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
