# Generated by Django 5.2.5 on 2025-09-04 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Le code postal doit contenir 5 chiffres', regex='^\\d{5}$')], verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
    ]
