# Generated by Django 5.2.5 on 2025-09-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_patient_code_postal_patient_commune_patient_rue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rue',
        ),
    ]
