# Generated by Django 5.2.5 on 2025-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_patient_code_postal_remove_patient_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type_patient',
            field=models.CharField(choices=[('femme', 'Femme'), ('bebe', 'Bébé')], default='femme', max_length=10, verbose_name='Type de patient'),
        ),
    ]
