# Generated by Django 5.2.5 on 2025-09-05 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_patient_type_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.FloatField(blank=True, help_text='Taille en mètres', null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.5)], verbose_name='Taille (m)')),
                ('poids', models.FloatField(blank=True, help_text='Poids en kilogrammes', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Poids (kg)')),
                ('medecin_traitant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médecin traitant')),
                ('gynecologue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gynécologue')),
                ('allergie', models.TextField(blank=True, help_text='Détail des allergies connues', null=True, verbose_name='Allergies')),
                ('asthme', models.BooleanField(default=False, verbose_name='Asthme')),
                ('raa', models.BooleanField(default=False, verbose_name='RAA (Rhumatisme articulaire aigu)')),
                ('diabete', models.BooleanField(default=False, verbose_name='Diabète')),
                ('hta', models.BooleanField(default=False, verbose_name='HTA (Hypertension artérielle)')),
                ('epilepsie', models.BooleanField(default=False, verbose_name='Épilepsie')),
                ('infection_urinaire', models.BooleanField(default=False, verbose_name='Infections urinaires récidivantes')),
                ('atcd_obstetricaux', models.TextField(blank=True, help_text='Grossesses précédentes, accouchements, complications...', null=True, verbose_name='Antécédents obstétricaux')),
                ('fcv_notes', models.TextField(blank=True, help_text='Notes générales sur le suivi FCV', null=True, verbose_name='Notes FCV')),
                ('atcd_fam_diabete', models.BooleanField(default=False, verbose_name='Diabète familial')),
                ('atcd_fam_hta', models.BooleanField(default=False, verbose_name='HTA familiale')),
                ('atcd_fam_cancer_sein', models.BooleanField(default=False, verbose_name='Cancer du sein familial')),
                ('atcd_fam_hypercholesterolemie', models.BooleanField(default=False, verbose_name='Hypercholestérolémie familiale')),
                ('atcd_fam_autre', models.TextField(blank=True, null=True, verbose_name='Autres antécédents familiaux')),
                ('atcd_chirurgicaux', models.TextField(blank=True, help_text='Interventions chirurgicales antérieures', null=True, verbose_name='Antécédents chirurgicaux')),
                ('contraception', models.TextField(blank=True, help_text='Méthodes contraceptives actuelles et passées', null=True, verbose_name='Contraception')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='core.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': '6.1.1 Antécédents',
                'verbose_name_plural': '6.1.1 Antécédents',
            },
        ),
        migrations.CreateModel(
            name='FrottisCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_frottis', models.DateField(verbose_name='Date du frottis')),
                ('resultat', models.CharField(help_text='Résultat du frottis cervico-vaginal', max_length=500, verbose_name='Résultat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antecedents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frottis', to='core.antecedents', verbose_name='Antécédents')),
            ],
            options={
                'verbose_name': 'Frottis cervico-vaginal',
                'verbose_name_plural': 'Frottis cervico-vaginaux',
                'ordering': ['-date_frottis'],
            },
        ),
    ]
