# Generated by Django 5.2.5 on 2025-09-05 21:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_antecedents_frottiscv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frottiscv',
            options={'ordering': ['-date_frottis'], 'verbose_name': '6.1.1.1 Frottis cervico-vaginal', 'verbose_name_plural': '6.1.1.1 Frottis cervico-vaginaux'},
        ),
        migrations.CreateModel(
            name='ConsultationGynecologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today, help_text="Date de la consultation (par défaut aujourd'hui)", verbose_name='Date de consultation')),
                ('tension_systolique', models.IntegerField(blank=True, help_text='Tension artérielle systolique en mmHg (80-250)', null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(250)], verbose_name='Tension systolique (mmHg)')),
                ('tension_diastolique', models.IntegerField(blank=True, help_text='Tension artérielle diastolique en mmHg (40-150)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)], verbose_name='Tension diastolique (mmHg)')),
                ('poids', models.FloatField(blank=True, help_text='Poids de la patiente en kilogrammes (30-200 kg)', null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(200.0)], verbose_name='Poids (kg)')),
                ('motif', models.TextField(help_text='Raison de la venue de la patiente', verbose_name='Motif de la consultation')),
                ('examen', models.TextField(blank=True, help_text="Résultats de l'examen gynécologique", verbose_name='Examen clinique')),
                ('prescription', models.TextField(blank=True, help_text='Prescription médicamenteuse ou recommandations', verbose_name='Prescription')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur la consultation', verbose_name='Notes complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_gynecologiques', to='core.patient', verbose_name='Patiente')),
            ],
            options={
                'verbose_name': '6.1.2 Consultation Gynécologique',
                'verbose_name_plural': '6.1.2 Consultations Gynécologiques',
                'ordering': ['-date_consultation', '-created_at'],
            },
        ),
    ]
