# Generated by Django 5.2.5 on 2025-09-06 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_frottiscv_options_consultationgynecologique'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationgynecologique',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Sage-femme qui a créé la consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sagefemme', verbose_name='Créé par'),
        ),
    ]
