# Generated by Django 5.2.5 on 2025-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_consultationgynecologique_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedents',
            name='atcd_medicaux_notes',
            field=models.TextField(blank=True, help_text='Notes complémentaires sur les antécédents médicaux', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='antecedents',
            name='atcd_fam_autre',
            field=models.TextField(blank=True, null=True, verbose_name='Notes/Autres antécédents'),
        ),
    ]
