# Generated by Django 5.2.5 on 2025-09-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_antecedents_atcd_medicaux_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneesGrossesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestite_parite', models.CharField(blank=True, help_text='Ex: G3P2', max_length=50, verbose_name='Gestité/Parité')),
                ('facteurs_risque', models.TextField(blank=True, verbose_name='Facteurs de risque')),
                ('lieu_accouchement', models.CharField(blank=True, max_length=100, verbose_name="Lieu d'accouchement prévu")),
                ('gs_rh', models.CharField(blank=True, help_text='Ex: A+, O-, AB+', max_length=10, verbose_name='GS Rh')),
                ('rai', models.CharField(blank=True, help_text="Recherche d'agglutinines irrégulières", max_length=20, verbose_name='RAI')),
                ('ht21', models.CharField(blank=True, help_text='Dépistage trisomie 21', max_length=20, verbose_name='HT21')),
                ('dpni', models.CharField(blank=True, help_text='Dépistage prénatal non invasif', max_length=20, verbose_name='DPNI')),
                ('toxo', models.CharField(blank=True, help_text='Sérologie toxoplasmose', max_length=20, verbose_name='Toxo')),
                ('rub', models.CharField(blank=True, help_text='Sérologie rubéole', max_length=20, verbose_name='Rub')),
                ('glyc_jeun', models.CharField(blank=True, help_text='Glycémie à jeun', max_length=20, verbose_name='Glyc à jeun')),
                ('hgpo', models.CharField(blank=True, help_text='Hyperglycémie provoquée par voie orale', max_length=50, verbose_name='HGPO')),
                ('ag_hbs', models.CharField(blank=True, help_text='Antigène HBs', max_length=20, verbose_name='Ag HBs')),
                ('ac_anti_hbs', models.CharField(blank=True, help_text='Anticorps anti HBs', max_length=20, verbose_name='Ac anti HBs')),
                ('vih', models.CharField(blank=True, max_length=20, verbose_name='VIH')),
                ('tpha_vdrl', models.CharField(blank=True, help_text='Sérologie syphilis', max_length=30, verbose_name='TPHA/VDRL')),
                ('hb', models.CharField(blank=True, help_text='Hémoglobine', max_length=20, verbose_name='Hb')),
                ('plaq', models.CharField(blank=True, help_text='Plaquettes', max_length=20, verbose_name='Plaq')),
                ('pv', models.CharField(blank=True, help_text='Prélèvement vaginal', max_length=50, verbose_name='PV')),
                ('ecbu', models.CharField(blank=True, help_text='Examen cytobactériologique des urines', max_length=50, verbose_name='ECBU')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'type_patient': 'femme'}, on_delete=django.db.models.deletion.CASCADE, related_name='donnees_grossesse', to='core.patient')),
            ],
            options={
                'verbose_name': 'Données de grossesse',
                'verbose_name_plural': 'Données de grossesse',
                'ordering': ['-updated_at'],
            },
        ),
    ]
