# Generated by Django 5.2.5 on 2025-09-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_consultationobstetricale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationobstetricale',
            options={'ordering': ['-date_consultation', '-created_at'], 'verbose_name': '6.1.3.2 Consultation Obstétricale', 'verbose_name_plural': '6.1.3.2 Consultations Obstétricales'},
        ),
        migrations.AlterModelOptions(
            name='donneesgrossesse',
            options={'ordering': ['-updated_at'], 'verbose_name': '6.1.3.1 Données de grossesse', 'verbose_name_plural': '6.1.3.1 Données de grossesse'},
        ),
        migrations.AddField(
            model_name='consultationobstetricale',
            name='semaines_amenorrhee',
            field=models.CharField(blank=True, help_text="Semaines d'aménorrhée au moment de la consultation (calculé automatiquement)", max_length=20, verbose_name="SA (Semaines d'Aménorrhée)"),
        ),
    ]
