# Generated by Django 5.2.5 on 2025-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_consultationobstetricale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationobstetricale',
            name='semaines_amenorrhee',
            field=models.CharField(blank=True, help_text="Semaines d'aménorrhée au moment de la consultation (calculé automatiquement)", max_length=50, verbose_name="SA (Semaines d'Aménorrhée)"),
        ),
    ]
