# Generated by Django 5.2.5 on 2025-09-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_consultationobstetricale_semaines_amenorrhee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntretienPrenatalPrecoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField(help_text="Date de réalisation de l'entretien prénatal précoce", verbose_name="Date de l'entretien")),
                ('semaines_amenorrhee', models.CharField(blank=True, help_text="Semaines d'aménorrhée calculées automatiquement", max_length=50, verbose_name="SA à la date de l'entretien")),
                ('conjoint_present', models.BooleanField(default=False, help_text="Le conjoint/partenaire était-il présent lors de l'entretien ?", verbose_name='Conjoint présent')),
                ('lieu_accouchement_prevu', models.CharField(blank=True, help_text="Maternité, clinique ou lieu prévu pour l'accouchement", max_length=200, verbose_name="Lieu d'accouchement prévu")),
                ('atcd_marquants', models.TextField(blank=True, help_text='Antécédents médicaux, obstétricaux ou chirurgicaux marquants', verbose_name='ATCD marquants')),
                ('environnement_social_familial', models.TextField(blank=True, help_text='Contexte socio-familial, soutien, conditions de vie', verbose_name='Environnement social et familial')),
                ('projet_naissance', models.TextField(blank=True, help_text="Souhaits et préférences pour l'accouchement et la naissance", verbose_name='Projet de naissance')),
                ('projet_parental', models.TextField(blank=True, help_text="Projet autour de la parentalité, préparation à l'arrivée de l'enfant", verbose_name='Projet parental')),
                ('ressenti', models.TextField(blank=True, help_text='Ressenti de la patiente et du conjoint sur la grossesse', verbose_name='Ressenti')),
                ('propositions_liens', models.TextField(blank=True, help_text="Orientations, propositions d'accompagnement, liens vers ressources", verbose_name='Propositions/Liens')),
                ('notes', models.TextField(blank=True, help_text='Observations et notes complémentaires', verbose_name='Notes complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to='core.sagefemme', verbose_name='Créé par')),
                ('patient', models.ForeignKey(limit_choices_to={'type_patient': 'femme'}, on_delete=django.db.models.deletion.CASCADE, related_name='entretiens_prenataux_precoces', to='core.patient', verbose_name='Patiente')),
                ('sage_femme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_prenataux_precoces', to='core.sagefemme', verbose_name='Sage-femme')),
            ],
            options={
                'verbose_name': '6.1.4 Entretien Prénatal Précoce',
                'verbose_name_plural': '6.1.4 Entretiens Prénataux Précoces',
                'ordering': ['-date_entretien', '-created_at'],
                'indexes': [models.Index(fields=['-date_entretien'], name='core_entret_date_en_5acbee_idx'), models.Index(fields=['patient', '-date_entretien'], name='core_entret_patient_86266b_idx')],
            },
        ),
    ]
