# Generated by Django 5.2.5 on 2025-09-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_entretienprenatalprecoce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretienprenatalprecoce',
            name='atcd_marquants',
        ),
        migrations.RemoveField(
            model_name='entretienprenatalprecoce',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='entretienprenatalprecoce',
            name='projet_naissance',
        ),
        migrations.RemoveField(
            model_name='entretienprenatalprecoce',
            name='projet_parental',
        ),
        migrations.AddField(
            model_name='entretienprenatalprecoce',
            name='atcd_marquants_sante',
            field=models.TextField(blank=True, help_text='Antécédents marquants et état de santé général', verbose_name='ATCD marquants et santé globale'),
        ),
        migrations.AddField(
            model_name='entretienprenatalprecoce',
            name='projet_naissance_parentalite',
            field=models.TextField(blank=True, help_text='Projet de naissance et préparation à la parentalité', verbose_name='Projet de naissance et de parentalité'),
        ),
        migrations.AlterField(
            model_name='entretienprenatalprecoce',
            name='propositions_liens',
            field=models.TextField(blank=True, help_text="Orientations, propositions d'accompagnement, liens vers ressources", verbose_name='Propositions/liens'),
        ),
    ]
