# Generated by Django 5.2.5 on 2025-09-12 20:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_update_epp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPreparationNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today, help_text='Date de la consultation de préparation à la naissance', verbose_name='Date de consultation')),
                ('semaines_amenorrhee', models.CharField(blank=True, help_text='Calculées automatiquement à partir de la DDG', max_length=20, null=True, verbose_name="Semaines d'aménorrhée")),
                ('theme_aborde', models.TextField(blank=True, help_text='Thème principal abordé lors de la consultation', verbose_name='')),
                ('a_prevoir', models.TextField(blank=True, help_text="Points à prévoir pour la prochaine consultation ou l'accouchement", verbose_name='À prévoir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_preparation_naissance_creees', to='core.sagefemme', verbose_name='Sage-femme créatrice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_preparation_naissance', to='core.patient', verbose_name='Patiente')),
            ],
            options={
                'verbose_name': '6.1.5 Consultation Préparation à la Naissance',
                'verbose_name_plural': '6.1.5 Consultations Préparation à la Naissance',
                'ordering': ['-date_consultation', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date_consultation'], name='core_consul_patient_9763bf_idx'), models.Index(fields=['created_by', 'date_consultation'], name='core_consul_created_2bed51_idx'), models.Index(fields=['date_consultation'], name='core_consul_date_co_1c7d7b_idx')],
            },
        ),
    ]
