# Generated by Django 5.2.5 on 2025-09-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_consultation_preparation_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpreparationnaissance',
            name='theme_aborde',
            field=models.TextField(blank=True, help_text="Thème(s) principal(aux) abordé(s) lors de la consultation", verbose_name="Thème(s) abordé(s)"),
        ),
    ]
