# Generated by Django 5.2.5 on 2025-09-16 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_update_consultation_preparation_naissance_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReeducationPerinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today, help_text='Date de la séance de rééducation du périnée', verbose_name='Date de la séance')),
                ('numero_seance', models.PositiveIntegerField(default=1, help_text='Numéro de la séance (commence à 1)', verbose_name='Numéro de séance')),
                ('examen_clinique_travail', models.TextField(blank=True, help_text='Examen clinique effectué et travail de rééducation réalisé lors de la séance', verbose_name='Examen clinique / Travail de rééducation')),
                ('a_prevoir', models.TextField(blank=True, help_text='Points à prévoir pour la prochaine séance ou recommandations', verbose_name='À prévoir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reeducations_perinee_creees', to='core.sagefemme', verbose_name='Sage-femme créatrice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reeducations_perinee', to='core.patient', verbose_name='Patiente')),
            ],
            options={
                'verbose_name': '6.1.6 Rééducation du Périnée',
                'verbose_name_plural': '6.1.6 Rééducations du Périnée',
                'ordering': ['-date_consultation', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date_consultation'], name='core_reeduc_patient_f5b84a_idx'), models.Index(fields=['created_by', 'date_consultation'], name='core_reeduc_created_fcd8ea_idx'), models.Index(fields=['date_consultation'], name='core_reeduc_date_co_66cd4f_idx'), models.Index(fields=['numero_seance'], name='core_reeduc_numero__3c9504_idx')],
            },
        ),
    ]
