# Generated by Django 5.2.5 on 2025-08-22 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageFemmeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Adresse email utilisée pour la connexion', max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet utilisateur peut se connecter', verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Indique si l'utilisateur peut accéder à l'administration", verbose_name='Staff')),
                ('must_change_password', models.BooleanField(default=True, help_text="Indique si l'utilisateur doit changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '1. Utilisateur Sage-femme',
                'verbose_name_plural': '1. Utilisateurs Sages-femmes',
                'db_table': 'core_sagefemme_user',
            },
        ),
    ]
