# Generated by Django 5.2.5 on 2025-08-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagefemmeuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sagefemmeuser',
            name='_is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet utilisateur peut se connecter (interne)', verbose_name='Actif'),
        ),
    ]
