# Generated by Django 5.2.5 on 2025-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_sagefemmeuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagefemmeuser',
            name='_is_active',
        ),
        migrations.AddField(
            model_name='sagefemmeuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet utilisateur peut se connecter', verbose_name='Actif'),
        ),
    ]
