# Generated by Django 5.2.5 on 2025-08-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_sagefemmeuser__is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sagefemmeuser',
            options={'verbose_name': '1. Utilisateur Sage-femme', 'verbose_name_plural': 'Utilisateurs Sages-femmes'},
        ),
    ]
